### ISSUE TITLE
Differentiate 379k classes

### ISSUE THREAD

**Issue by kassandrasmith** [smkanvinde/UTECEClasses#2]
EE379k corresponds to several classes (e.g. "HIGH THROUGHPUT NANOPATTERNING," "SMART GRIDS," "INFORMATION SECURITY & PRIVACY," "24-DATA SCIENCE LABORATORY," etc. ) and they are subject to change. 

There should be an option for which EE 379k a user means.

**Comment by smkanvinde** [comment]
Workaround added in b5c9424
